@baseUrl = http://localhost:3001

# MESSAGES
###
GET {{baseUrl}}/messages/
# ?limit=10
# &offset=0

###
GET {{baseUrl}}/messages/1/

###
POST {{baseUrl}}/messages/
Content-Type: application/json

{
  "text": "Olá Eduarda!",
  "from": "Erick",
  "to": "Eduarda"
}


### Atualiza um reacado
PATCH {{baseUrl}}/messages/3/
Content-Type: application/json

{
  "read": true
}

### Apaga um recado
DELETE {{baseUrl}}/messages/1/


#


# Pessoa
### Lista todas as pessoas
GET {{baseUrl}}/persons/
# ?limit=10
# &offset=0

###
GET {{baseUrl}}/persons/11/

###
POST {{baseUrl}}/persons/
Content-Type: application/json

{
  "name": "Erick",
  "email": "berdnaski1177@gmail.com",
  "password": "123456"
}

### Atualiza um reacado
PATCH {{baseUrl}}/persons/11/
Content-Type: application/json

{
  "password": "654321",
  "nome": "João"
}

### Apaga um recado
DELETE {{baseUrl}}/persons/9/
