@baseUrl = http://localhost:3001

# MESSAGES
###
GET {{baseUrl}}/messages/
# ?limit=10
# &offset=0

###
GET {{baseUrl}}/messages/2/

###
POST {{baseUrl}}/messages/
Content-Type: application/json

{
  "text": "4Novo recado",
  "from": "Erick",
  "to": "Eduarda",
  "read": false,
  "date": "2025-05-13T19:24:20.975Z"
}

### Atualiza um reacado
PATCH {{baseUrl}}/messages/2/
Content-Type: application/json

{
  "text": "Novo recado",
  "from": "Erick",
  "to": "Eduarda",
  "read": false,
  "date": "2025-05-13T19:24:20.975Z"
}

### Apaga um recado
DELETE {{baseUrl}}/messages/2/